name: Publish Packages
on:
  workflow_dispatch:

env:
  NPM_CONFIG_PROVENANCE: true
  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v3

      - name: Install primary node version (see volta config in package.json) and dependencies
        uses: ./.github/actions/install-node-and-dependencies

      - run: npx lerna publish from-package -y
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
